name: action setup lf
author: Erling Rennemo Jellum
description: Install the LF toolchain
branding:
  icon: clock
  color: blue

inputs:
  lfc-version:
    description: 'The version of the LF compiler to install. `stable` or `nightly`'
    required: true
    default: 'stable'
  lingo-version:
    description: 'The version of the lingo to install. `stable` or version number'
    required: true
    default: 'stable'

runs:
  using: composite
  steps:
    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Checkout LF Install Script repo
      uses: actions/checkout@v4
      with:
        repository: 'lf-lang/installation'
        path: 'tmp/installation'
    - name: Install LFC (linux)
      if: runner.os == 'Linux'
      run: |
        bash ./tmp/installation/install.sh cli ${{ inputs.lfc-version }}
      shell: bash
    - name: Install LFC (macOS)
      if: runner.os == 'macOS'
      run: |
        bash ./tmp/installation/install.sh cli ${{ inputs.lfc-version }} --prefix=$HOME/.local && break
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      shell: bash
    - name: Install lingo
      run: |
        if [ "${{ inputs.lingo-version }}" = "stable" ]; then
          cargo install lingua-franca
        else
          cargo install lingua-franca --version ${{ inputs.lingo-version }}
        fi
      shell: bash
